### PR TITLE
Refactor wheel and libtorch build scripts

### PR DESCRIPTION
**Pull request by jataylo**
Draft PR.

### CODE REVIEW

**Comment by jataylo** [comment]
This PR refactors build_rocm.sh to reduce the number of manually specified paths and library version numbers in order to reduce future debugging time. This PR also will only include the Tensile/Kernel files for the specified architectures which will reduce the wheel size:

**Updates**
-   Instead of manually listing the Tensile/Kernels files for all architectures this update replaces
    this functionality and will automatically grab all files related to the specified
    archs listed in PYTORCH_ROCM_ARCH and any non-arch specific files e.g. TensileLibrary.dat
-  No longer required to specify the full .so name (with number) for ROCm libraries
           - The .so versions are copied and the patching code will fix the links to point to this version
- No longer required to specify paths for ROCm libraries allowing the removal of the large switch
           - Paths are acquired programmatically with find
- No longer required to specify both the path and filename for the OS specific libraries
           - Programatically extract file name from the path
           
**CI logs**
**rocm5.2 - BUILD_WHEELS=1**

- CI: http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/73/

**rocm5.1.1 - BUILD_WHEELS=1 BUILD_LIBTORCH=1**

- CI: http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/79/

**rocm5.0 - BUILD_WHEELS=1 BUILD_LIBTORCH=1**

- CI: http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/75/


**Notes/Future Updates**
For now the full so library name is for the OS specific libraries as there are instances when a non numbered so version does not exist.

**Comment by jataylo** [comment]
PR passes the CI

**rocm5.2 (passing logs)** http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/118/
**rocm5.1.1 (passing logs)**http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/119/
**rocm5.0 (passing logs)** http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/123/

I will rebase into two commits, one for the common code and one for build_rocm.sh

**Comment by jataylo** [comment]
Rebased into 2 commits @jithunnair-amd @jeffdaily, CI logs passing in the tests in the above comment

**Update to so patching for ROCm**
Wildcard used in grep to grab the actual numbered so file referenced
in patchelf. This allows the removal of specifying the so number in
DEPS_LIST & DEPS_SONAME

This commit also adds the functionality for trimming so names to
build_libtorch.sh from build_common.sh

**Refactor to remove switch statement in build_rocm.sh**
This commit refactors build_rocm.sh and brings in a few major updates:
 - No longer required to specify the full .so name (with number) for ROCm libraries
       - The .so versions are copied and the patching code will fix the links to point to this version
 - No longer required to specify paths for ROCm libraries allowing the removal of the large switch
       - Paths are acquired programmatically with find
 - No longer required to specify both the path and filename for the OS specific libraries
       - Programatically extract file name from the path
 - Automatically extract Tensile/Kernels files for the architectures specified in PYTORCH_ROCM_ARCH
   and any non-arch specific files e.g. TensileLibrary.dat

**Comment by jithunnair-amd** [comment]
Tested with ROCm5.3 as well: http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/159/

**Pull request merged**
